### ISSUE TITLE
Trait implementations for `Recycled`

### ISSUE THREAD

**Issue by jonhoo** [zslayton/lifeguard#15]
Currently, `Recycled` doesn't forward very many traits, even if the underlying type implements them. In particular, fairly standard traits such as `Clone`, `PartialOrd` or `Hash` are inaccessible through `Recycled` and `RcRecycled`. This makes the wrapper type much harder to work with, and is pretty easy to fix. The impls section of [Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html) provides a fairly good list of traits that it's good for wrapper types to proxy.

**Comment by zslayton** [comment]
This is a great idea. Unfortunately, I don't have time to implement it at the moment. PRs are welcome if you have the time!

**Comment by zslayton** [comment]
The fix for this added implementations for:
* `PartialEq`
* `Eq`
* `PartialOrd`
* `Ord`
* `Hash`
* `Clone`

PRs forwarding other traits from `std` are welcome.
