### ISSUE TITLE
add hashed pool

### ISSUE THREAD

**Issue by vitiral** [zslayton/lifeguard#20]
I love the library!

I've tossed around a similar idea for [artifact](https://github.com/vitiral/artifact), and actually implemented it but didn't find much performance benefit. Maybe you can improve on my idea...

My application used a fair amount of `Arc` data types, but many of them were constructed from the user. Because of this, items that could simply be a pointer to an existing `Arc` end up being allocated anyway.

I'm not sure if lifeguard could offer an API for this, but I figured it was worth mentioning. I think keeping `lifeguard` as-is (as a focused library) is probably preferred, but thought you might find the idea intriguing :smile:

**Comment by zslayton** [comment]
> I love the library!

Thanks!

> My application used a fair amount of Arc data types, but many of them were constructed from the user. Because of this, items that could simply be a pointer to an existing Arc end up being allocated anyway.

I'm not sure I totally followed this. Could you give me an example?

**Comment by vitiral** [comment]
My tool parses text files and looks for requirement tags. For simplicity (not really a working example) let's say you had two files with the following:

**file1.txt**
```
See:
- #REQ-foo
- #REQ-bar
```

**file2.txt**
```
These are good:
- #REQ-foo
- #REQ-baz
```

`REQ-foo` is used twice, but my tool will end up creating two `Arc(String("REQ-foo"))` items, because it doesn't know that an identical object already exists. This takes up more memory.

It occurs to me that this is actually a completely different goal to this library -- since you can't really "reuse" an `Arc`, only dedup them. So I'm closing this :smile:
