### ISSUE TITLE
Heads-up: UB due to misuse of mem::uninitialized will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [zslayton/lifeguard#25]
[Here](https://github.com/zslayton/lifeguard/blob/c133e7edb3c0c01051780cabf48c2a05b511e21c/src/lib.rs#L347), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it produces a value of an arbitrary  type `T` with `mem::uninitialized()`. In the near future the call to `mem::uninitialized()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/66059), and [our crater run](https://github.com/rust-lang/rust/pull/66059#issuecomment-575164263) determined that this crate will be affected.

`mem::uninitialized()` is deprecated since Rust 1.39. The intended replacement is [`MaybeUninit`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html), which tracks the possibility of uninitialized values at the type level to make sure the compiler does not make any false assumptions. I see you are using `ManuallyDrop`; likely the fix will involve replacing that by `MaybeUninit`.

**Comment by bbqsrc** [comment]
Any movement in #26? I am receiving complaints of build errors for one of [our production dependencies](https://github.com/divvun/divvunspell).

@zslayton: I understand that you had an experimental branch that might resolve this issue, though it has not been pushed to github.

If you do not have the time to maintain this crate any further, please by all means let us know. I'd be happy to assist with maintaining the crate as we rely on it and will for quite some time. :smile:

**Comment by antonok-edm** [comment]
@zslayton @bbqsrc we're also using this in production, and will need to be able to build on arm64 macOS quite soon - please let me know if there's anything I can do to assist with this effort :smiley:

**Comment by zslayton** [comment]
Hi all, thanks for the nudge. I'll try to find some time to address this in the next few days.

I also appreciate the offers to help! I've been experimenting with a branch that exposes an API similar to [the one described in this comment](https://github.com/zslayton/lifeguard/issues/21#issuecomment-438735256). I think it's more flexible and am thinking I'd like to move in that direction before a 1.0 is released. Any input from `lifeguard` users would be great.

**Comment by zslayton** [comment]
@bbqsrc @antonok-edm: I've published this fix as part of the new `v0.6.1` release.
